name: build-linux-wheels

on:
  push:
    branches: [ master ]

jobs:
  build-manylinux-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["cp38-manylinux_x86_64", "cp39-manylinux_x86_64", "cp310-manylinux_x86_64", "cp311-manylinux_x86_64", "cp312-manylinux_x86_64",  "cp313-manylinux_x86_64"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (runner)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade cibuildwheel twine

      - name: Build manylinux wheels with cibuildwheel
        env:
          # Target CPython versions (align with former matrix)
          CIBW_BUILD: ${{ matrix.python-version }}
        #   CIBW_BUILD: "cp310-manylinux_x86_64"
          # Skip PyPy & musllinux for now
          CIBW_SKIP: "pp* *musllinux*"
          # Install system deps (runs inside manylinux container)
          CIBW_BEFORE_ALL_LINUX: >-
            yum install -y epel-release &&
            yum install -y cmake3 libXrandr-devel libXinerama-devel libXcursor-devel libXi-devel mesa-libGLU-devel
          # Provide flags similar to prior pip-wheel-args (handled via env; setup.py could be adapted to read these)
          EXTRA_CMAKE_DEFINES: "-DUSE_AVX=Off -DCI_BUILD=On"
          # Verbosity
          CIBW_BUILD_VERBOSITY: "1"
        run: |
          # If needed, adapt setup.py to consume EXTRA_CMAKE_DEFINES; for now rely on defaults.
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels artifact
        uses: actions/upload-artifact@v4
        with:
          name: pypbd-${{matrix.python-version}}
          path: wheelhouse
        if: always()

      - name: Publish wheels to PyPI
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload wheelhouse/*-manylinux*.whl --skip-existing
